[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-added-large-files", args = ['--maxkb=100'] },
  { id = "check-case-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "check-json" },
  { id = "check-merge-conflict", args = [ "--assume-in-merge" ] },
  { id = "check-toml" },
  { id = "check-xml" },
  { id = "check-yaml" },
  { id = "detect-private-key" },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "mixed-line-ending", args = [ "--fix=lf" ] },
  { id = "no-commit-to-branch", args = [ "--branch", "main" ] },
  { id = "trailing-whitespace" }
]
